require('config.set_up.project_config')
require('config.set_up.telescope')
require('config.set_up.treesitter')
require('config.set_up.hop')
require('config.set_up.lualine')
--require('config.set_up.trouble')
require('config.set_up.saga')
require('config.set_up.lualine')
require('config.set_up.cmp')
require('config.set_up.lspkind')
require('config.set_up.webdevicons')
require('config.set_up.prettier')
require('config.set_up.bufferline' )
require('config.set_up.lsp-saga')
require('config.set_up.autopairs')
